import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:iett/model.dart';

class GETAPI extends StatefulWidget {
  @override
  _GETAPIState createState() => _GETAPIState();
}

class _GETAPIState extends State<GETAPI> {
  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return Scaffold(
      appBar: buildAppBar(),
      body: Container(
          width: size.width, height: size.height, child: _placeHolderWidget),
      floatingActionButton:
          FloatingActionButton(onPressed: postApi, child: Icon(Icons.add)),
    );
  }

  AppBar buildAppBar() => AppBar(
        title: Text("API"),
        centerTitle: true,
      );

  Widget get _placeHolderWidget => FutureBuilder<List<Geo>>(
        future: getApi(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            if (snapshot.hasData) {
              var auto = snapshot.data;
              return ListView(
                  children: auto
                      .map((e) => ListTile(
                            title: Text(e.lat),
                            subtitle: Text(e.lng),
                          ))
                      .toList());
            } else
              return Text("Error");
          } else if (snapshot.connectionState == ConnectionState.waiting) {
            return Center(child: CircularProgressIndicator());
          } else {
            return Text("There is connection problem");
          }
        },
      );

  Future<List<Geo>> getApi() async {
    List<Geo> list = [];
    http.Response _response =
        await http.get("https://jsonplaceholder.typicode.com/users");
    var responseJson = json.decode(_response.body);
    for (var i = 0; i < responseJson.length; i++) {
      Geo geo = Geo.fromJson(responseJson[i]['address']['geo']);
      list.add(geo);
    }
    return list;
  }

  Future<bool> postApi() async {
    Autogenerated autogenerated = new Autogenerated();
    autogenerated.id=22;
    autogenerated.name = "Kayabey";
    autogenerated.username = "flutterboy";
    autogenerated.email = "slalasl";
    autogenerated.phone = "56554";
    autogenerated.company=Company(name:"sdsa",catchPhrase: "sdas",bs: "dklskld");
    autogenerated.website="sdfsdf";
    autogenerated.address = Address(
        street: "Dart mah.",
        suite: "Google apt.",
        city: "FlutterCity",
        zipcode: "45245",
        geo: Geo(lat: "4521", lng: "5245"));

    http.Response _response = await http.put(
        "https://firecode-6fb9f-default-rtdb.firebaseio.com/persons/1.json",
        body: json.encode(autogenerated.toJson()));

    if (_response.statusCode == 200) {
      return true;
    } else {
      return false;
    }
  }
}
